services:
  secure:
    build: .
    container_name: whodx_secure_env
    ports:
      - "443:443"
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
      - /secure-data:size=100m
    environment:
      - SESSION_TIME=15
    restart: unless-stopped
